DEFAULT_FONT_SIZE: int = 16
DEFAULT_FONT_NAME: str = "Consolas"

DEFAULT_BUTTON_WIDTH: int = 128
DEFAULT_BUTTON_HEIGHT: int = 48
DEFAULT_BUTTON_TEXT: str = "Click me!"
DEFAULT_BUTTON_TEXT_PADDING: int = 8
DEFAULT_BUTTON_BORDER_WIDTH: int = 2
DEFAULT_BUTTON_BORDER_RADIUS: int = 4

DEFAULT_BUTTON_IMAGE_PADDING: int = 4

DEFAULT_CHECKBOX_SIZE: int = 24
DEFAULT_CHECKBOX_BORDER_RADIUS: int = DEFAULT_BUTTON_BORDER_RADIUS
DEFAULT_CHECKBOX_BORDER_WIDTH: int = DEFAULT_BUTTON_BORDER_WIDTH
DEFAULT_CHECKBOX_TEXT_PADDING: int = DEFAULT_BUTTON_TEXT_PADDING
DEFAULT_CHECKBOX_CHECK_PADDING: int = 6

DEFAULT_CONTAINER_PADDING: int = 8
DEFAULT_CONTAINER_SPACING: int = 8
DEFAULT_CONTAINER_BORDER_RADIUS: int = DEFAULT_BUTTON_BORDER_RADIUS
DEFAULT_CONTAINER_BORDER_WIDTH: int = DEFAULT_BUTTON_BORDER_WIDTH

DEFAULT_TEXTINPUT_BORDER_RADIUS: int = 4
DEFAULT_TEXTINPUT_BORDER_WIDTH: int = DEFAULT_BUTTON_BORDER_WIDTH
DEFAULT_TEXTINPUT_WIDTH: int = 360
DEFAULT_TEXTINPUT_HEIGHT: int = 36
DEFAULT_TEXTINPUT_TEXT_PADDING: int = DEFAULT_BUTTON_TEXT_PADDING
DEFAULT_TEXTINPUT_PLACEHOLDER: str = "Enter text..."

CURSOR_FLASH_INTERVAL: float = 0.5
DEFAULT_DRAG_THRESHOLD: int = 5

DEFAULT_SWITCH_HEIGHT = 32
DEFAULT_SWITCH_BORDER_RADIUS = DEFAULT_SWITCH_HEIGHT // 2
DEFAULT_SWITCH_BORDER_WIDTH = DEFAULT_BUTTON_BORDER_WIDTH
DEFAULT_SWITCH_PADDING = 4
DEFAULT_SWITCH_TEXT_PADDING = 8