DEFAULT_FONT_SIZE = 16
DEFAULT_FONT_NAME = "Consolas"

DEFAULT_BUTTON_WIDTH = 128
DEFAULT_BUTTON_HEIGHT = 48
DEFAULT_BUTTON_TEXT = "Click me!"
DEFAULT_BUTTON_TEXT_PADDING = 8
DEFAULT_BUTTON_BORDER_WIDTH = 2
DEFAULT_BUTTON_BORDER_RADIUS = 4

DEFAULT_BUTTON_IMAGE_PADDING = 4

DEFAULT_CHECKBOX_SIZE = 24
DEFAULT_CHECKBOX_BORDER_RADIUS = DEFAULT_BUTTON_BORDER_RADIUS
DEFAULT_CHECKBOX_BORDER_WIDTH = DEFAULT_BUTTON_BORDER_WIDTH
DEFAULT_CHECKBOX_TEXT_PADDING = DEFAULT_BUTTON_TEXT_PADDING
DEFAULT_CHECKBOX_CHECK_PADDING = 6