[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "buttonup"
version = "0.1.0"
dependencies = [
    "pygame>=2.6.1",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["buttonup*"]
exclude = ["example_assets*", "tests*", "example_*"]

[tool.setuptools.package-data]
buttonup = ["themes/*.json"]
